import type { ReservedHintDirective } from "~/src/utils/hint-reserved-label-directives";
import {
  FILE_COPY_ICON_PATH,
  HINT_ATTACH_ICON_PATH,
  HINT_CANCEL_ICON_PATH,
  HINT_DELETE_ICON_PATH,
  HINT_DISLIKE_ICON_PATH,
  HINT_DOWNLOAD_ICON_PATH,
  HINT_HIDE_ICON_PATH,
  HINT_HOME_ICON_PATH,
  HINT_INPUT_ICON_PATH,
  HINT_LIKE_ICON_PATH,
  HINT_LOGIN_ICON_PATH,
  HINT_MICROPHONE_ICON_PATH,
  HINT_NEXT_ICON_PATH,
  HINT_PREV_ICON_PATH,
  HINT_SAVE_ICON_PATH,
  HINT_SHARE_ICON_PATH,
  HINT_SIDEBAR_ICON_PATH,
  HINT_SUBMIT_ICON_PATH
} from "~/src/lib/inline-icons";

export const HINT_DIRECTIVE_ICON_PATHS: Record<ReservedHintDirective, string> = {
  input: HINT_INPUT_ICON_PATH,
  attach: HINT_ATTACH_ICON_PATH,
  share: HINT_SHARE_ICON_PATH,
  download: HINT_DOWNLOAD_ICON_PATH,
  login: HINT_LOGIN_ICON_PATH,
  microphone: HINT_MICROPHONE_ICON_PATH,
  delete: HINT_DELETE_ICON_PATH,
  save: HINT_SAVE_ICON_PATH,
  copy: FILE_COPY_ICON_PATH,
  hide: HINT_HIDE_ICON_PATH,
  home: HINT_HOME_ICON_PATH,
  sidebar: HINT_SIDEBAR_ICON_PATH,
  next: HINT_NEXT_ICON_PATH,
  prev: HINT_PREV_ICON_PATH,
  cancel: HINT_CANCEL_ICON_PATH,
  submit: HINT_SUBMIT_ICON_PATH,
  like: HINT_LIKE_ICON_PATH,
  dislike: HINT_DISLIKE_ICON_PATH
};