import { describe, test } from "bun:test";
import { runDirectiveCase } from "~/tests/helpers/hint-directive";
import type { DirectiveTestCase } from "~/tests/types";

export const directiveTestCase: DirectiveTestCase = {
  desc: "detects next-navigation controls while ignoring sign-in prompts",
  test: {
    recognizes: [
      "<a href='/next' rel='next'>Next</a>",
      "<ytd-button-renderer button-tooltip-position='left' class='style-scope ytd-shorts' button-renderer='' button-next=''><yt-button-shape><button class='yt-spec-button-shape-next yt-spec-button-shape-next--text yt-spec-button-shape-next--mono yt-spec-button-shape-next--size-xl yt-spec-button-shape-next--icon-button yt-spec-button-shape-next--enable-backdrop-filter-experiment' title='' aria-label='Next video'><div aria-hidden='true' class='yt-spec-button-shape-next__icon'><span class='ytIconWrapperHost' style='width: 24px; height: 24px;'><span class='yt-icon-shape ytSpecIconShapeHost'><div style='width: 100%; height: 100%; display: block; fill: currentcolor;'><svg xmlns='http://www.w3.org/2000/svg' height='24' viewBox='0 0 24 24' width='24' focusable='false' aria-hidden='true' style='pointer-events: none; display: inherit; width: 100%; height: 100%;'><path d='M12 3a1 1 0 00-1 1v13.586l-5.293-5.293a1 1 0 10-1.414 1.414L12 21.414l7.707-7.707a1 1 0 10-1.414-1.414L13 17.586V4a1 1 0 00-1-1Z'></path></svg></div></span></span></div><yt-touch-feedback-shape aria-hidden='true' class='yt-spec-touch-feedback-shape yt-spec-touch-feedback-shape--touch-response yt-spec-touch-feedback-shape--down'><div class='yt-spec-touch-feedback-shape__stroke'></div><div class='yt-spec-touch-feedback-shape__fill'></div></yt-touch-feedback-shape></button></yt-button-shape><tp-yt-paper-tooltip offset='8' role='tooltip' tabindex='-1' aria-label='tooltip' style='left: -96.3333px; top: 3.02083px;'><div id='tooltip' class='style-scope tp-yt-paper-tooltip fade-in-animation' style-target='tooltip'>Next video</div></tp-yt-paper-tooltip></ytd-button-renderer>"
    ],
    ignored: [
      "<button>Other</button>",
      "<ytd-button-renderer id='sign-in-button' class='style-scope ytd-guide-signin-promo-renderer' button-renderer='' button-next=''><yt-button-shape><a href='https://accounts.google.com/ServiceLogin?service=youtube&amp;uilel=3&amp;passive=true&amp;continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252Fshorts%252FiCRUap0AEMQ&amp;hl=en' rel='nofollow' class='yt-spec-button-shape-next yt-spec-button-shape-next--outline yt-spec-button-shape-next--call-to-action yt-spec-button-shape-next--size-m yt-spec-button-shape-next--icon-leading yt-spec-button-shape-next--enable-backdrop-filter-experiment' aria-haspopup='false' force-new-state='true' aria-label='Sign in' aria-current='false' aria-disabled='false' style=''><div aria-hidden='true' class='yt-spec-button-shape-next__icon'><span class='ytIconWrapperHost' style='width: 24px; height: 24px;'><span class='yt-icon-shape ytSpecIconShapeHost'><div style='width: 100%; height: 100%; display: block; fill: currentcolor;'><svg xmlns='http://www.w3.org/2000/svg' height='24' viewBox='0 0 24 24' width='24' focusable='false' aria-hidden='true' style='pointer-events: none; display: inherit; width: 100%; height: 100%;'><path d='M12 1C5.925 1 1 5.925 1 12s4.925 11 11 11 11-4.925 11-11S18.075 1 12 1Zm0 2a9 9 0 016.447 15.276 7 7 0 00-12.895 0A9 9 0 0112 3Zm0 2a4 4 0 100 8 4 4 0 000-8Zm0 2a2 2 0 110 4 2 2 0 010-4Zm-.1 9.001L11.899 16a5 5 0 014.904 3.61A8.96 8.96 0 0112 21a8.96 8.96 0 01-4.804-1.391 5 5 0 014.704-3.608Z'></path></svg></div></span></span></div><div class='yt-spec-button-shape-next__button-text-content'><span class='yt-core-attributed-string yt-core-attributed-string--white-space-no-wrap' role='text' style=''>Sign in</span></div><yt-touch-feedback-shape aria-hidden='true' class='yt-spec-touch-feedback-shape yt-spec-touch-feedback-shape--touch-response'><div class='yt-spec-touch-feedback-shape__stroke'></div><div class='yt-spec-touch-feedback-shape__fill'></div></yt-touch-feedback-shape></a></yt-button-shape><tp-yt-paper-tooltip offset='8' disable-upgrade=''></tp-yt-paper-tooltip></ytd-button-renderer>"
    ]
  }
};

describe("next directive", () => {
  test(directiveTestCase.desc, () => {
    runDirectiveCase("next", directiveTestCase.test);
  });
});