#!/usr/bin/env sh
set -e

git diff --cached --name-only -z --diff-filter=ACMR -- '*.js' '*.jsx' '*.mjs' '*.cjs' '*.ts' '*.tsx' '*.json' '*.html' |
while IFS= read -r -d '' file; do
  bunx oxfmt --write "$file"
  git add "$file"
done
